### ISSUE TITLE
Создать Mindmap модального окна тестирования блока (верстка)

### ISSUE THREAD

**Issue by konar24** [modular-platform-it/QA#14]
https://miro.com/app/board/uXjVKYbJHU8=/?moveToWidget=3458764584849768382&cot=14

**Comment by Barkaleva** [comment]
Модальное окно тестирования блока
— отображает блок близко к тому как он будет выглядеть в телеграм
— эмулирует работу меню и вопросов
— при нажатии на пункт меню или ответы на вопросы совершает запрос к апи и отображает ответ в виде JSON. Если пункт меню ссылается на другой блок открывает его.
![image](https://github.com/modular-platform-it/QA/assets/145904584/4a249e27-7ffa-4839-8c04-1cb0cedd0d64)
